# Generated by Django 2.1.7 on 2020-05-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_documento_registro_hora_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Registro_Hora_Extra',
        ),
    ]
